
# Site settings
title: Yilin Ye
name: Yilin Ye
subtitle:  Computer Scientist
email: yyebd@connect.ust.hk
description: >
  Computer Scientist
baseurl: ""
url: "https://yilinye.github.io/"
github_username:  yilin
disqus_baseurl: "https://yilinye.github.io/"
disqus_shortname: https-yilinye-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yilin Ye"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/yilinye
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Yilin Ye
    url: https://www.linkedin.com/in/paul-e-soto-2705ab218
    desc: Connect with me on LinkedIn
    share: true
